import Head from "next/head";
import { Inter } from "@next/font/google";
import Hero from "@/components/Hero";
import Footer from "@/components/Footer";
import Feature from "@/components/Feature";
import Panel from "@/components/Panel";
import Panel2 from "@/components/Panel2";
import Ghost2 from "@/public/assets/ghostmascot.png";
import SwordShield from "@/public/assets/swordshield.png";
import Ghost1 from "@/public/assets/aaveLend.png";
import Newsletter from "@/components/Newsletter";
import Glow2 from "@/public/assets/glow2.png";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  return (
    <>
      <Head>
        <title>sAAVE Finance | Landing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <Feature />
        <Panel
          img={Ghost1}
          glowimg={"glow-1"}
          title={"Decentralized lending"}
          desc={
            "In return for securing the services on the Cronos Hub, transaction fees and staking rewards are distributed to HEDRON stakers."
          }
          link={"https://www.google.com"}
        />
        <Panel2
          img={SwordShield}
          glowimg={Glow2}
          title={"Decentralized lending"}
          desc={
            "In return for securing the services on the Cronos Hub, transaction fees and staking rewards are distributed to HEDRON stakers."
          }
          link={"https://www.google.com"}
        />
        <Panel
          img={Ghost2}
          glowimg={"glow-3"}
          title={"Decentralized lending"}
          desc={
            "In return for securing the services on the Cronos Hub, transaction fees and staking rewards are distributed to HEDRON stakers. In the Cronos Hub, transaction fees and staking rewards are distributed to HEDRON stakers."
          }
          link={"https://www.google.com"}
        />
        <Newsletter />
        <Footer />
      </main>
    </>
  );
}
