import Head from "next/head";
import { Inter } from "@next/font/google";
import Hero from "@/components/Hero";
import Hero2 from "@/components/Hero2";
import Footer from "@/components/Footer/Footer";
import Feature from "@/components/Feature";
import Panel from "@/components/Panel";
import Panel2 from "@/components/Panel2";
import Ghost2 from "../public/assets/SAAVE.png";
import SwordShield from "@/public/assets/swordshield.png";
import Ghost1 from "@/public/assets/aaveLend.png";
import Newsletter from "@/components/Cards/Newsletter";
import Glow1 from "@/public/assets/glow1.png";
import Glow2 from "@/public/assets/glow2.png";
import Glow3 from "@/public/assets/glow3.png";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  return (
    <>
      <Head>
        <title>Saave Finance | Landing</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero2 />
        <Feature />
        <Panel
          img={Ghost1}
          glowimg={Glow1}
          title={"AAVE"}
          desc={
            "The AAVE protocol is a decentralized finance (DeFi) platform built on top of the Ethereum blockchain. DeFi refers to a new type of financial system that is built on blockchain technology....."
          }
          link={"/aave"}
        />
        <Panel2
          img={Ghost2}
          glowimg={Glow2}
          title={"Curve Finance"}
          desc={
            "Curve Finance is a decentralized finance (DeFi) platform that allows users to trade stablecoins and earn fees in the process. Stablecoins are cryptocurrencies that are pegged to the value of a stable asset....."
          }
          link={"/curve"}
        />
        <Panel
          img={SwordShield}
          glowimg={Glow3}
          title={"Decentralized Finance"}
          desc={
            "DeFi stands for Decentralized Finance, which refers to a new type of financial system that is built using blockchain technology. Blockchain is a digital ledger that is distributed ....."
          }
          link={"/defi"}
        />
        <Newsletter />
        <Footer />
      </main>
    </>
  );
}
